### ISSUE TITLE
navicat查询错误

### ISSUE THREAD

**Issue by bwcxyk** [1340691923/ElasticView#40]
选择筛选条件两个模糊查询时，服务异常
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbf28aa]

goroutine 39 [running]:
github.com/olivere/elastic/v7.(*BoolQuery).Source(0xc0006e4000)
	C:/Users/Administrator/go/pkg/mod/github.com/olivere/elastic/v7@v7.0.24/search_queries_bool.go:123 +0xaaa
github.com/olivere/elastic/v7.(*BoolQuery).Source(0xc0006e40a0)
	C:/Users/Administrator/go/pkg/mod/github.com/olivere/elastic/v7@v7.0.24/search_queries_bool.go:115 +0xea
github.com/olivere/elastic/v7.(*SearchSource).Source(0xc00033d118)
	C:/Users/Administrator/go/pkg/mod/github.com/olivere/elastic/v7@v7.0.24/search_source.go:395 +0x272
github.com/1340691923/ElasticView/platform-basic-libs/service/es.EsServiceV7.CrudGetDSL({{0x0, {0x0, 0x0}, {0x0, 0x0}}, {}, 0xc000364540}, 0xc0006dc080, 0xc0006be180)
	D:/CodeApply/WORK/JAVA/ElasticView/platform-basic-libs/service/es/EsServiceV7.go:770 +0x1f4
github.com/1340691923/ElasticView/api.EsCrudController.GetDSL({{{0x0, {0x0, 0x0}, {0x0, 0x0}}, {}}}, 0xc0003da2c0)
	D:/CodeApply/WORK/JAVA/ElasticView/api/EsCrudController.go:51 +0xb1
github.com/gofiber/fiber/v2.(*App).next(0xc00000a1e0, 0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go:132 +0x1d8
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go:792 +0x53
github.com/1340691923/ElasticView/middleware.Rbac(0x0)
	D:/CodeApply/WORK/JAVA/ElasticView/middleware/Rbac.go:33 +0xd5
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0006ba000)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go:789 +0x43
github.com/1340691923/ElasticView/middleware.JwtMiddleware(0xc0006a4700)
	D:/CodeApply/WORK/JAVA/ElasticView/middleware/jwt.go:51 +0x466
github.com/gofiber/fiber/v2.(*Ctx).Next(0x8)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go:789 +0x43
github.com/1340691923/ElasticView/middleware.Timer(0x118ddc0)
	D:/CodeApply/WORK/JAVA/ElasticView/middleware/Time.go:16 +0x49
github.com/gofiber/fiber/v2.(*App).next(0xc00000a1e0, 0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go:132 +0x1d8
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0006a4970)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go:792 +0x53
github.com/gofiber/fiber/v2/middleware/filesystem.New.func1(0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/middleware/filesystem/filesystem.go:111 +0xc5
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc00014e1c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go:789 +0x43
github.com/gofiber/fiber/v2/middleware/compress.New.func3(0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/middleware/compress/compress.go:54 +0x45
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000140318)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go:789 +0x43
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/middleware/cors/cors.go:141 +0x292
github.com/gofiber/fiber/v2.(*App).next(0xc00000a1e0, 0xc0001242c0)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go:132 +0x1d8
github.com/gofiber/fiber/v2.(*App).handler(0xc00000a1e0, 0x4bde37)
	C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go:160 +0x45
github.com/valyala/fasthttp.(*Server).serveConn(0xc0006286c0, {0x1b4e440, 0xc000560e80})
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/server.go:2328 +0x120e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000c0460, 0xc000552a40)
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go:223 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go:195 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
	C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go:194 +0x1b5
```

**Comment by 1340691923** [comment]
新版本已经修复，还没来得及上传github，可以加群获取
